// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ36ple8_2Z6-VnISMm3-W3XEaZTPz77o',
    appId: '1:94918049363:web:bafc47ac9aae98eb66d0a6',
    messagingSenderId: '94918049363',
    projectId: 'calorie-check-c786c',
    authDomain: 'calorie-check-c786c.firebaseapp.com',
    storageBucket: 'calorie-check-c786c.appspot.com',
    measurementId: 'G-QNWRBNYGZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3r5p4r1QUCCurOFJWeuuZIDBBvLTY874',
    appId: '1:94918049363:android:5c160cd16c7b68e966d0a6',
    messagingSenderId: '94918049363',
    projectId: 'calorie-check-c786c',
    storageBucket: 'calorie-check-c786c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv_cWjdJlxsvUnVaLJMjke2JOVUVx8RM0',
    appId: '1:94918049363:ios:83017cfe29e716fd66d0a6',
    messagingSenderId: '94918049363',
    projectId: 'calorie-check-c786c',
    storageBucket: 'calorie-check-c786c.appspot.com',
    androidClientId: '94918049363-q2ipf60h5deeg1cnil8mo1sombcloe5j.apps.googleusercontent.com',
    iosClientId: '94918049363-d36m88gu2fokqbv5sd8l8vnnfvieph9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieCheck',
  );
}
